# Generated by Django 4.2 on 2026-05-22 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_date', models.DateField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='procurement.invoice')),
            ],
            options={
                'verbose_name': 'Акт приёмки',
                'verbose_name_plural': 'Акты приёмки',
            },
        ),
        migrations.CreateModel(
            name='SerialCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('is_unique', models.BooleanField(default=True)),
                ('acceptance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_checks', to='warehouse.materialacceptance')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Проверка серийного номера',
                'verbose_name_plural': 'Проверки серийных номеров',
            },
        ),
        migrations.CreateModel(
            name='QuantityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_quantity', models.PositiveIntegerField()),
                ('actual_quantity', models.PositiveIntegerField()),
                ('result', models.CharField(blank=True, choices=[('match', 'Совпадает'), ('mismatch', 'Расхождение')], max_length=20)),
                ('acceptance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_checks', to='warehouse.materialacceptance')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Проверка количества',
                'verbose_name_plural': 'Проверки количества',
            },
        ),
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviation_type', models.CharField(choices=[('underdelivery', 'Недовложение'), ('overdelivery', 'Излишек'), ('duplicate_sn', 'Дубликат серийного номера')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('acceptance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='warehouse.materialacceptance')),
                ('detected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отклонение',
                'verbose_name_plural': 'Отклонения',
            },
        ),
    ]
